plugins:
  - rubocop-rake
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 3.2
  NewCops: enable
  SuggestExtensions: false
  Exclude:
    - 'vendor/**/*'
    - 'tmp/**/*'
    - 'pkg/**/*'

Style/StringLiterals:
  EnforcedStyle: single_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: single_quotes

Style/BlockDelimiters:
  EnforcedStyle: semantic

Layout/LineLength:
  Max: 120

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
    - '*.gemspec'

Metrics/MethodLength:
  Max: 22

Metrics/AbcSize:
  Max: 20

Layout/CaseIndentation:
  IndentOneStep: false
  EnforcedStyle: end

Layout/EndAlignment:
  EnforcedStyleAlignWith: variable

Layout/FirstHashElementIndentation:
  EnforcedStyle: consistent

Layout/FirstArrayElementIndentation:
  EnforcedStyle: consistent

Layout/MultilineHashBraceLayout:
  EnforcedStyle: new_line

Layout/MultilineArrayBraceLayout:
  EnforcedStyle: new_line

# RSpec cops configuration

RSpec/DescribeClass:
  Exclude:
    - 'spec/integration/**/*'

RSpec/ExampleLength:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

RSpec/BeforeAfterAll:
  Exclude:
    - 'spec/integration/**/*'

RSpec/InstanceVariable:
  Exclude:
    - 'spec/integration/**/*'

RSpec/SpecFilePathFormat:
  Enabled: false

RSpec/NoExpectationExample:
  Enabled: false

RSpec/RepeatedDescription:
  Enabled: false

RSpec/IteratedExpectation:
  Enabled: false

RSpec/VerifiedDoubles:
  Enabled: false

RSpec/StubbedMock:
  Enabled: false

RSpec/MessageSpies:
  Enabled: false
