# frozen_string_literal: true

RSpec.describe 'Atlassian Jira' do
  subject(:client) { WSDL::Client.new WSDL.parse(fixture('wsdl/jira')) }

  it 'returns a map of services and ports' do
    expect(client.services).to eq(
      'JiraSoapServiceService' => {
        ports: {
          'jirasoapservice-v2' => {
            type: 'http://schemas.xmlsoap.org/wsdl/soap/',
            location: 'https://jira.atlassian.com/rpc/soap/jirasoapservice-v2',
            operations: [
              { name: 'getComment' },
              { name: 'getConfiguration' },
              { name: 'createGroup' },
              { name: 'getServerInfo' },
              { name: 'getGroup' },
              { name: 'createUser' },
              { name: 'addComment' },
              { name: 'createIssue' },
              { name: 'getComponents' },
              { name: 'getUser' },
              { name: 'updateUser' },
              { name: 'updateGroup' },
              { name: 'addUserToGroup' },
              { name: 'removeUserFromGroup' },
              { name: 'getIssue' },
              { name: 'updateIssue' },
              { name: 'deleteIssue' },
              { name: 'getAvailableActions' },
              { name: 'getSecurityLevel' },
              { name: 'createProject' },
              { name: 'updateProject' },
              { name: 'getProjectByKey' },
              { name: 'removeAllRoleActorsByProject' },
              { name: 'getPriorities' },
              { name: 'getResolutions' },
              { name: 'getIssueTypes' },
              { name: 'getSubTaskIssueTypes' },
              { name: 'getStatuses' },
              { name: 'getIssueTypesForProject' },
              { name: 'getProjectRoles' },
              { name: 'getProjectRole' },
              { name: 'getProjectRoleActors' },
              { name: 'getDefaultRoleActors' },
              { name: 'removeAllRoleActorsByNameAndType' },
              { name: 'deleteProjectRole' },
              { name: 'updateProjectRole' },
              { name: 'createProjectRole' },
              { name: 'isProjectRoleNameUnique' },
              { name: 'addActorsToProjectRole' },
              { name: 'removeActorsFromProjectRole' },
              { name: 'addDefaultActorsToProjectRole' },
              { name: 'removeDefaultActorsFromProjectRole' },
              { name: 'getAssociatedNotificationSchemes' },
              { name: 'getAssociatedPermissionSchemes' },
              { name: 'deleteProject' },
              { name: 'getProjectById' },
              { name: 'getVersions' },
              { name: 'getComments' },
              { name: 'getFavouriteFilters' },
              { name: 'releaseVersion' },
              { name: 'archiveVersion' },
              { name: 'getFieldsForCreate' },
              { name: 'getFieldsForEdit' },
              { name: 'getSubTaskIssueTypesForProject' },
              { name: 'getCustomFields' },
              { name: 'logout' },
              { name: 'editComment' },
              { name: 'login' },
              { name: 'getProjectWithSchemesById' },
              { name: 'getSecurityLevels' },
              { name: 'getProjectAvatars' },
              { name: 'setProjectAvatar' },
              { name: 'getProjectAvatar' },
              { name: 'deleteProjectAvatar' },
              { name: 'getNotificationSchemes' },
              { name: 'getPermissionSchemes' },
              { name: 'createPermissionScheme' },
              { name: 'deletePermissionScheme' },
              { name: 'addPermissionTo' },
              { name: 'deletePermissionFrom' },
              { name: 'getAllPermissions' },
              { name: 'createIssueWithSecurityLevel' },
              { name: 'hasPermissionToEditComment' },
              { name: 'getFieldsForAction' },
              { name: 'progressWorkflowAction' },
              { name: 'getIssueById' },
              { name: 'addAttachmentsToIssue' },
              { name: 'getAttachmentsFromIssue' },
              { name: 'addWorklogWithNewRemainingEstimate' },
              { name: 'addWorklogAndAutoAdjustRemainingEstimate' },
              { name: 'addWorklogAndRetainRemainingEstimate' },
              { name: 'deleteWorklogAndAutoAdjustRemainingEstimate' },
              { name: 'deleteWorklogAndRetainRemainingEstimate' },
              { name: 'deleteWorklogWithNewRemainingEstimate' },
              { name: 'updateWorklogAndAutoAdjustRemainingEstimate' },
              { name: 'updateWorklogAndRetainRemainingEstimate' },
              { name: 'updateWorklogWithNewRemainingEstimate' },
              { name: 'getWorklogs' },
              { name: 'hasPermissionToCreateWorklog' },
              { name: 'hasPermissionToDeleteWorklog' },
              { name: 'hasPermissionToUpdateWorklog' },
              { name: 'getResolutionDateByKey' },
              { name: 'getResolutionDateById' },
              { name: 'getIssueCountForFilter' },
              { name: 'getIssuesFromTextSearch' },
              { name: 'getIssuesFromTextSearchWithProject' },
              { name: 'getIssuesFromJqlSearch' },
              { name: 'setUserPassword' },
              { name: 'deleteUser' },
              { name: 'deleteGroup' },
              { name: 'refreshCustomFields' },
              { name: 'getProjectsNoSchemes' },
              { name: 'addVersion' },
              { name: 'getSavedFilters' },
              { name: 'createIssueWithParent' },
              { name: 'createIssueWithParentWithSecurityLevel' },
              { name: 'addBase64EncodedAttachmentsToIssue' },
              { name: 'createProjectFromObject' },
              { name: 'getSecuritySchemes' },
              { name: 'getIssuesFromFilter' },
              { name: 'getIssuesFromFilterWithLimit' },
              { name: 'getIssuesFromTextSearchWithLimit' },
              { name: 'setNewProjectAvatar' }
            ]
          }
        }
      }
    )
  end

  it 'raises an error because RPC/encoded operations are not' do
    service = 'JiraSoapServiceService'
    port = 'jirasoapservice-v2'

    expect { client.operation(service, port, 'updateGroup') }
      .to raise_error(WSDL::UnsupportedStyleError, %r{"updateGroup" is an "rpc/encoded" style operation})
  end
end
