# frozen_string_literal: true

RSpec.describe 'RATP' do
  subject(:client) { WSDL::Client.new WSDL.parse(fixture('wsdl/ratp')) }

  let(:service_name) { :Wsiv }
  let(:port_name)    { :WsivSOAP11port_http }

  it 'returns a map of services and ports' do
    expect(client.services).to eq(
      'Wsiv' => {
        ports: {
          'WsivSOAP11port_http' => {
            type: 'http://schemas.xmlsoap.org/wsdl/soap/',
            location: 'http://www.ratp.fr/wsiv/services/Wsiv',
            operations: [
              { name: 'getItineraries' },
              { name: 'getMissionsFrequency' },
              { name: 'getMissionsFirstLast' },
              { name: 'getStationAreas' },
              { name: 'getVersion' },
              { name: 'getLines' },
              { name: 'getStations' },
              { name: 'getMissionsNext' },
              { name: 'getDirections' },
              { name: 'getMission' },
              { name: 'getPerturbations' },
              { name: 'getGeoPoints' }
            ]
          },
          'WsivSOAP12port_http' => {
            type: 'http://schemas.xmlsoap.org/wsdl/soap12/',
            location: 'http://www.ratp.fr/wsiv/services/Wsiv',
            operations: [
              { name: 'getItineraries' },
              { name: 'getMissionsFrequency' },
              { name: 'getMissionsFirstLast' },
              { name: 'getStationAreas' },
              { name: 'getVersion' },
              { name: 'getLines' },
              { name: 'getStations' },
              { name: 'getMissionsNext' },
              { name: 'getDirections' },
              { name: 'getMission' },
              { name: 'getPerturbations' },
              { name: 'getGeoPoints' }
            ]
          }
        }
      }
    )
  end

  it 'gracefully handle recursive type definitions' do
    service = 'Wsiv'
    port = 'WsivSOAP11port_http'
    operation = client.operation(service, port, 'getStations')

    expect(operation.soap_action).to eq('urn:getStations')
    expect(operation.endpoint).to eq('http://www.ratp.fr/wsiv/services/Wsiv')

    ns1 = 'http://wsiv.ratp.fr'
    ns2 = 'http://wsiv.ratp.fr/xsd'

    expect(operation.contract.request.body.paths).to eq([
      { path: ['getStations'],
        kind: :complex,
        namespace: ns1,
        form: 'qualified',
        singular: true,
        min_occurs: '1',
        max_occurs: '1',
        wildcard: false },
      { path: %w[getStations station],
        kind: :complex,
        namespace: ns1,
        form: 'qualified',
        singular: true,
        min_occurs: '0',
        max_occurs: '1',
        wildcard: false },
      { path: %w[getStations station direction],
        kind: :complex,
        namespace: ns2,
        form: 'qualified',
        singular: true,
        min_occurs: '0',
        max_occurs: '1',
        wildcard: false },
      { path: %w[getStations station direction line],
        kind: :complex,
        namespace: ns2,
        form: 'qualified',
        singular: true,
        min_occurs: '0',
        max_occurs: '1',
        wildcard: false },
      { path: %w[getStations station direction line code],
        kind: :simple,
        namespace: ns2,
        form: 'qualified',
        singular: true,
        min_occurs: '0',
        max_occurs: '1',
        type: 'xs:string',
        list: false },
      { path: %w[getStations station direction line codeStif],
        kind: :simple,
        namespace: ns2,
        form: 'qualified',
        singular: true,
        min_occurs: '0',
        max_occurs: '1',
        type: 'xs:string',
        list: false },
      { path: %w[getStations station direction line id],
        kind: :simple,
        namespace: ns2,
        form: 'qualified',
        singular: true,
        min_occurs: '0',
        max_occurs: '1',
        type: 'xs:string',
        list: false },
      { path: %w[getStations station direction line image],
        kind: :simple,
        namespace: ns2,
        form: 'qualified',
        singular: true,
        min_occurs: '0',
        max_occurs: '1',
        type: 'xs:string',
        list: false },
      { path: %w[getStations station direction line name],
        kind: :simple,
        namespace: ns2,
        form: 'qualified',
        singular: true,
        min_occurs: '0',
        max_occurs: '1',
        type: 'xs:string',
        list: false },
      { path: %w[getStations station direction line realm],
        kind: :simple,
        namespace: ns2,
        form: 'qualified',
        singular: true,
        min_occurs: '0',
        max_occurs: '1',
        type: 'xs:string',
        list: false },
      { path: %w[getStations station direction line reseau],
        kind: :complex,
        namespace: ns2,
        form: 'qualified',
        singular: true,
        min_occurs: '0',
        max_occurs: '1',
        wildcard: false },
      { path: %w[getStations station direction line reseau code],
        kind: :simple,
        namespace: ns2,
        form: 'qualified',
        singular: true,
        min_occurs: '0',
        max_occurs: '1',
        type: 'xs:string',
        list: false },
      { path: %w[getStations station direction line reseau id],
        kind: :simple,
        namespace: ns2,
        form: 'qualified',
        singular: true,
        min_occurs: '0',
        max_occurs: '1',
        type: 'xs:string',
        list: false },
      { path: %w[getStations station direction line reseau image],
        kind: :simple,
        namespace: ns2,
        form: 'qualified',
        singular: true,
        min_occurs: '0',
        max_occurs: '1',
        type: 'xs:string',
        list: false },
      { path: %w[getStations station direction line reseau name],
        kind: :simple,
        namespace: ns2,
        form: 'qualified',
        singular: true,
        min_occurs: '0',
        max_occurs: '1',
        type: 'xs:string',
        list: false },
      { path: %w[getStations station direction name],
        kind: :simple,
        namespace: ns2,
        form: 'qualified',
        singular: true,
        min_occurs: '0',
        max_occurs: '1',
        type: 'xs:string',
        list: false },
      { path: %w[getStations station direction sens],
        kind: :simple,
        namespace: ns2,
        form: 'qualified',
        singular: true,
        min_occurs: '0',
        max_occurs: '1',
        type: 'xs:string',
        list: false },
      { path: %w[getStations station direction stationsEndLine],
        kind: :recursive,
        namespace: ns2,
        form: 'qualified',
        singular: false,
        min_occurs: '0',
        max_occurs: 'unbounded',
        recursive_type: 'ax21:Station' },
      { path: %w[getStations station geoPointA],
        kind: :complex,
        namespace: ns2,
        form: 'qualified',
        singular: true,
        min_occurs: '0',
        max_occurs: '1',
        wildcard: false },
      { path: %w[getStations station geoPointA id],
        kind: :simple,
        namespace: ns2,
        form: 'qualified',
        singular: true,
        min_occurs: '0',
        max_occurs: '1',
        type: 'xs:string',
        list: false },
      { path: %w[getStations station geoPointA name],
        kind: :simple,
        namespace: ns2,
        form: 'qualified',
        singular: true,
        min_occurs: '0',
        max_occurs: '1',
        type: 'xs:string',
        list: false },
      { path: %w[getStations station geoPointA nameSuffix],
        kind: :simple,
        namespace: ns2,
        form: 'qualified',
        singular: true,
        min_occurs: '0',
        max_occurs: '1',
        type: 'xs:string',
        list: false },
      { path: %w[getStations station geoPointA type],
        kind: :simple,
        namespace: ns2,
        form: 'qualified',
        singular: true,
        min_occurs: '0',
        max_occurs: '1',
        type: 'xs:string',
        list: false },
      { path: %w[getStations station geoPointA x],
        kind: :simple,
        namespace: ns2,
        form: 'qualified',
        singular: true,
        min_occurs: '0',
        max_occurs: '1',
        type: 'xs:double',
        list: false },
      { path: %w[getStations station geoPointA y],
        kind: :simple,
        namespace: ns2,
        form: 'qualified',
        singular: true,
        min_occurs: '0',
        max_occurs: '1',
        type: 'xs:double',
        list: false },
      { path: %w[getStations station geoPointR],
        kind: :complex,
        namespace: ns2,
        form: 'qualified',
        singular: true,
        min_occurs: '0',
        max_occurs: '1',
        wildcard: false },
      { path: %w[getStations station geoPointR id],
        kind: :simple,
        namespace: ns2,
        form: 'qualified',
        singular: true,
        min_occurs: '0',
        max_occurs: '1',
        type: 'xs:string',
        list: false },
      { path: %w[getStations station geoPointR name],
        kind: :simple,
        namespace: ns2,
        form: 'qualified',
        singular: true,
        min_occurs: '0',
        max_occurs: '1',
        type: 'xs:string',
        list: false },
      { path: %w[getStations station geoPointR nameSuffix],
        kind: :simple,
        namespace: ns2,
        form: 'qualified',
        singular: true,
        min_occurs: '0',
        max_occurs: '1',
        type: 'xs:string',
        list: false },
      { path: %w[getStations station geoPointR type],
        kind: :simple,
        namespace: ns2,
        form: 'qualified',
        singular: true,
        min_occurs: '0',
        max_occurs: '1',
        type: 'xs:string',
        list: false },
      { path: %w[getStations station geoPointR x],
        kind: :simple,
        namespace: ns2,
        form: 'qualified',
        singular: true,
        min_occurs: '0',
        max_occurs: '1',
        type: 'xs:double',
        list: false },
      { path: %w[getStations station geoPointR y],
        kind: :simple,
        namespace: ns2,
        form: 'qualified',
        singular: true,
        min_occurs: '0',
        max_occurs: '1',
        type: 'xs:double',
        list: false },
      { path: %w[getStations station id],
        kind: :simple,
        namespace: ns2,
        form: 'qualified',
        singular: true,
        min_occurs: '0',
        max_occurs: '1',
        type: 'xs:string',
        list: false },
      { path: %w[getStations station idsNextA],
        kind: :simple,
        namespace: ns2,
        form: 'qualified',
        singular: false,
        min_occurs: '0',
        max_occurs: 'unbounded',
        type: 'xs:string',
        list: false },
      { path: %w[getStations station idsNextR],
        kind: :simple,
        namespace: ns2,
        form: 'qualified',
        singular: false,
        min_occurs: '0',
        max_occurs: 'unbounded',
        type: 'xs:string',
        list: false },
      { path: %w[getStations station line],
        kind: :complex,
        namespace: ns2,
        form: 'qualified',
        singular: true,
        min_occurs: '0',
        max_occurs: '1',
        wildcard: false },
      { path: %w[getStations station line code],
        kind: :simple,
        namespace: ns2,
        form: 'qualified',
        singular: true,
        min_occurs: '0',
        max_occurs: '1',
        type: 'xs:string',
        list: false },
      { path: %w[getStations station line codeStif],
        kind: :simple,
        namespace: ns2,
        form: 'qualified',
        singular: true,
        min_occurs: '0',
        max_occurs: '1',
        type: 'xs:string',
        list: false },
      { path: %w[getStations station line id],
        kind: :simple,
        namespace: ns2,
        form: 'qualified',
        singular: true,
        min_occurs: '0',
        max_occurs: '1',
        type: 'xs:string',
        list: false },
      { path: %w[getStations station line image],
        kind: :simple,
        namespace: ns2,
        form: 'qualified',
        singular: true,
        min_occurs: '0',
        max_occurs: '1',
        type: 'xs:string',
        list: false },
      { path: %w[getStations station line name],
        kind: :simple,
        namespace: ns2,
        form: 'qualified',
        singular: true,
        min_occurs: '0',
        max_occurs: '1',
        type: 'xs:string',
        list: false },
      { path: %w[getStations station line realm],
        kind: :simple,
        namespace: ns2,
        form: 'qualified',
        singular: true,
        min_occurs: '0',
        max_occurs: '1',
        type: 'xs:string',
        list: false },
      { path: %w[getStations station line reseau],
        kind: :complex,
        namespace: ns2,
        form: 'qualified',
        singular: true,
        min_occurs: '0',
        max_occurs: '1',
        wildcard: false },
      { path: %w[getStations station line reseau code],
        kind: :simple,
        namespace: ns2,
        form: 'qualified',
        singular: true,
        min_occurs: '0',
        max_occurs: '1',
        type: 'xs:string',
        list: false },
      { path: %w[getStations station line reseau id],
        kind: :simple,
        namespace: ns2,
        form: 'qualified',
        singular: true,
        min_occurs: '0',
        max_occurs: '1',
        type: 'xs:string',
        list: false },
      { path: %w[getStations station line reseau image],
        kind: :simple,
        namespace: ns2,
        form: 'qualified',
        singular: true,
        min_occurs: '0',
        max_occurs: '1',
        type: 'xs:string',
        list: false },
      { path: %w[getStations station line reseau name],
        kind: :simple,
        namespace: ns2,
        form: 'qualified',
        singular: true,
        min_occurs: '0',
        max_occurs: '1',
        type: 'xs:string',
        list: false },
      { path: %w[getStations station name],
        kind: :simple,
        namespace: ns2,
        form: 'qualified',
        singular: true,
        min_occurs: '0',
        max_occurs: '1',
        type: 'xs:string',
        list: false },
      { path: %w[getStations station stationArea],
        kind: :complex,
        namespace: ns2,
        form: 'qualified',
        singular: true,
        min_occurs: '0',
        max_occurs: '1',
        wildcard: false },
      { path: %w[getStations station stationArea access],
        kind: :complex,
        namespace: ns2,
        form: 'qualified',
        singular: false,
        min_occurs: '0',
        max_occurs: 'unbounded',
        wildcard: false },
      { path: %w[getStations station stationArea access address],
        kind: :simple,
        namespace: ns2,
        form: 'qualified',
        singular: true,
        min_occurs: '0',
        max_occurs: '1',
        type: 'xs:string',
        list: false },
      { path: %w[getStations station stationArea access id],
        kind: :simple,
        namespace: ns2,
        form: 'qualified',
        singular: true,
        min_occurs: '0',
        max_occurs: '1',
        type: 'xs:string',
        list: false },
      { path: %w[getStations station stationArea access index],
        kind: :simple,
        namespace: ns2,
        form: 'qualified',
        singular: true,
        min_occurs: '0',
        max_occurs: '1',
        type: 'xs:string',
        list: false },
      { path: %w[getStations station stationArea access name],
        kind: :simple,
        namespace: ns2,
        form: 'qualified',
        singular: true,
        min_occurs: '0',
        max_occurs: '1',
        type: 'xs:string',
        list: false },
      { path: %w[getStations station stationArea access timeDaysLabel],
        kind: :simple,
        namespace: ns2,
        form: 'qualified',
        singular: true,
        min_occurs: '0',
        max_occurs: '1',
        type: 'xs:string',
        list: false },
      { path: %w[getStations station stationArea access timeDaysStatus],
        kind: :simple,
        namespace: ns2,
        form: 'qualified',
        singular: true,
        min_occurs: '0',
        max_occurs: '1',
        type: 'xs:string',
        list: false },
      { path: %w[getStations station stationArea access timeEnd],
        kind: :simple,
        namespace: ns2,
        form: 'qualified',
        singular: true,
        min_occurs: '0',
        max_occurs: '1',
        type: 'xs:string',
        list: false },
      { path: %w[getStations station stationArea access timeStart],
        kind: :simple,
        namespace: ns2,
        form: 'qualified',
        singular: true,
        min_occurs: '0',
        max_occurs: '1',
        type: 'xs:string',
        list: false },
      { path: %w[getStations station stationArea access x],
        kind: :simple,
        namespace: ns2,
        form: 'qualified',
        singular: true,
        min_occurs: '0',
        max_occurs: '1',
        type: 'xs:double',
        list: false },
      { path: %w[getStations station stationArea access y],
        kind: :simple,
        namespace: ns2,
        form: 'qualified',
        singular: true,
        min_occurs: '0',
        max_occurs: '1',
        type: 'xs:double',
        list: false },
      { path: %w[getStations station stationArea id],
        kind: :simple,
        namespace: ns2,
        form: 'qualified',
        singular: true,
        min_occurs: '0',
        max_occurs: '1',
        type: 'xs:string',
        list: false },
      { path: %w[getStations station stationArea name],
        kind: :simple,
        namespace: ns2,
        form: 'qualified',
        singular: true,
        min_occurs: '0',
        max_occurs: '1',
        type: 'xs:string',
        list: false },
      { path: %w[getStations station stationArea stations],
        kind: :recursive,
        namespace: ns2,
        form: 'qualified',
        singular: false,
        min_occurs: '0',
        max_occurs: 'unbounded',
        recursive_type: 'ax21:Station' },
      { path: %w[getStations station stationArea tarifsToParis],
        kind: :complex,
        namespace: ns2,
        form: 'qualified',
        singular: false,
        min_occurs: '0',
        max_occurs: 'unbounded',
        wildcard: false },
      { path: %w[getStations station stationArea tarifsToParis demiTarif],
        kind: :simple,
        namespace: ns2,
        form: 'qualified',
        singular: true,
        min_occurs: '0',
        max_occurs: '1',
        type: 'xs:float',
        list: false },
      { path: %w[getStations station stationArea tarifsToParis pleinTarif],
        kind: :simple,
        namespace: ns2,
        form: 'qualified',
        singular: true,
        min_occurs: '0',
        max_occurs: '1',
        type: 'xs:float',
        list: false },
      { path: %w[getStations station stationArea tarifsToParis viaLine],
        kind: :complex,
        namespace: ns2,
        form: 'qualified',
        singular: true,
        min_occurs: '0',
        max_occurs: '1',
        wildcard: false },
      { path: %w[getStations station stationArea tarifsToParis viaLine code],
        kind: :simple,
        namespace: ns2,
        form: 'qualified',
        singular: true,
        min_occurs: '0',
        max_occurs: '1',
        type: 'xs:string',
        list: false },
      { path: %w[getStations station stationArea tarifsToParis viaLine codeStif],
        kind: :simple,
        namespace: ns2,
        form: 'qualified',
        singular: true,
        min_occurs: '0',
        max_occurs: '1',
        type: 'xs:string',
        list: false },
      { path: %w[getStations station stationArea tarifsToParis viaLine id],
        kind: :simple,
        namespace: ns2,
        form: 'qualified',
        singular: true,
        min_occurs: '0',
        max_occurs: '1',
        type: 'xs:string',
        list: false },
      { path: %w[getStations station stationArea tarifsToParis viaLine image],
        kind: :simple,
        namespace: ns2,
        form: 'qualified',
        singular: true,
        min_occurs: '0',
        max_occurs: '1',
        type: 'xs:string',
        list: false },
      { path: %w[getStations station stationArea tarifsToParis viaLine name],
        kind: :simple,
        namespace: ns2,
        form: 'qualified',
        singular: true,
        min_occurs: '0',
        max_occurs: '1',
        type: 'xs:string',
        list: false },
      { path: %w[getStations station stationArea tarifsToParis viaLine realm],
        kind: :simple,
        namespace: ns2,
        form: 'qualified',
        singular: true,
        min_occurs: '0',
        max_occurs: '1',
        type: 'xs:string',
        list: false },
      { path: %w[getStations station stationArea tarifsToParis viaLine reseau],
        kind: :complex,
        namespace: ns2,
        form: 'qualified',
        singular: true,
        min_occurs: '0',
        max_occurs: '1',
        wildcard: false },
      { path: %w[getStations station stationArea tarifsToParis viaLine reseau code],
        kind: :simple,
        namespace: ns2,
        form: 'qualified',
        singular: true,
        min_occurs: '0',
        max_occurs: '1',
        type: 'xs:string',
        list: false },
      { path: %w[getStations station stationArea tarifsToParis viaLine reseau id],
        kind: :simple,
        namespace: ns2,
        form: 'qualified',
        singular: true,
        min_occurs: '0',
        max_occurs: '1',
        type: 'xs:string',
        list: false },
      { path: %w[getStations station stationArea tarifsToParis viaLine reseau image],
        kind: :simple,
        namespace: ns2,
        form: 'qualified',
        singular: true,
        min_occurs: '0',
        max_occurs: '1',
        type: 'xs:string',
        list: false },
      { path: %w[getStations station stationArea tarifsToParis viaLine reseau name],
        kind: :simple,
        namespace: ns2,
        form: 'qualified',
        singular: true,
        min_occurs: '0',
        max_occurs: '1',
        type: 'xs:string',
        list: false },
      { path: %w[getStations station stationArea tarifsToParis viaReseau],
        kind: :complex,
        namespace: ns2,
        form: 'qualified',
        singular: true,
        min_occurs: '0',
        max_occurs: '1',
        wildcard: false },
      { path: %w[getStations station stationArea tarifsToParis viaReseau code],
        kind: :simple,
        namespace: ns2,
        form: 'qualified',
        singular: true,
        min_occurs: '0',
        max_occurs: '1',
        type: 'xs:string',
        list: false },
      { path: %w[getStations station stationArea tarifsToParis viaReseau id],
        kind: :simple,
        namespace: ns2,
        form: 'qualified',
        singular: true,
        min_occurs: '0',
        max_occurs: '1',
        type: 'xs:string',
        list: false },
      { path: %w[getStations station stationArea tarifsToParis viaReseau image],
        kind: :simple,
        namespace: ns2,
        form: 'qualified',
        singular: true,
        min_occurs: '0',
        max_occurs: '1',
        type: 'xs:string',
        list: false },
      { path: %w[getStations station stationArea tarifsToParis viaReseau name],
        kind: :simple,
        namespace: ns2,
        form: 'qualified',
        singular: true,
        min_occurs: '0',
        max_occurs: '1',
        type: 'xs:string',
        list: false },
      { path: %w[getStations station stationArea zoneCarteOrange],
        kind: :simple,
        namespace: ns2,
        form: 'qualified',
        singular: true,
        min_occurs: '0',
        max_occurs: '1',
        type: 'xs:string',
        list: false },
      { path: %w[getStations gp],
        kind: :complex,
        namespace: ns1,
        form: 'qualified',
        singular: true,
        min_occurs: '0',
        max_occurs: '1',
        wildcard: false },
      { path: %w[getStations gp id],
        kind: :simple,
        namespace: ns2,
        form: 'qualified',
        singular: true,
        min_occurs: '0',
        max_occurs: '1',
        type: 'xs:string',
        list: false },
      { path: %w[getStations gp name],
        kind: :simple,
        namespace: ns2,
        form: 'qualified',
        singular: true,
        min_occurs: '0',
        max_occurs: '1',
        type: 'xs:string',
        list: false },
      { path: %w[getStations gp nameSuffix],
        kind: :simple,
        namespace: ns2,
        form: 'qualified',
        singular: true,
        min_occurs: '0',
        max_occurs: '1',
        type: 'xs:string',
        list: false },
      { path: %w[getStations gp type],
        kind: :simple,
        namespace: ns2,
        form: 'qualified',
        singular: true,
        min_occurs: '0',
        max_occurs: '1',
        type: 'xs:string',
        list: false },
      { path: %w[getStations gp x],
        kind: :simple,
        namespace: ns2,
        form: 'qualified',
        singular: true,
        min_occurs: '0',
        max_occurs: '1',
        type: 'xs:double',
        list: false },
      { path: %w[getStations gp y],
        kind: :simple,
        namespace: ns2,
        form: 'qualified',
        singular: true,
        min_occurs: '0',
        max_occurs: '1',
        type: 'xs:double',
        list: false },
      { path: %w[getStations distances],
        kind: :simple,
        namespace: ns1,
        form: 'qualified',
        singular: false,
        min_occurs: '0',
        max_occurs: 'unbounded',
        type: 'xs:int',
        list: false },
      { path: %w[getStations limit],
        kind: :simple,
        namespace: ns1,
        form: 'qualified',
        singular: true,
        min_occurs: '0',
        max_occurs: '1',
        type: 'xs:int',
        list: false },
      { path: %w[getStations sortAlpha],
        kind: :simple,
        namespace: ns1,
        form: 'qualified',
        singular: true,
        min_occurs: '0',
        max_occurs: '1',
        type: 'xs:boolean',
        list: false }
    ])
  end

  it 'builds a request' do
    operation = client.operation(service_name, port_name, :getStations)

    operation.prepare do
      body do
        tag('getStations') do
          tag('station') do
            tag('id', 1975)
          end
          tag('limit', 1)
        end
      end
    end

    expected = Nokogiri.XML(%(
      <env:Envelope
          xmlns:ns0="http://wsiv.ratp.fr"
          xmlns:ns1="http://wsiv.ratp.fr/xsd"
          xmlns:env="http://schemas.xmlsoap.org/soap/envelope/">
        <env:Header/>
        <env:Body>
          <ns0:getStations>
            <ns0:station>
              <ns1:id>1975</ns1:id>
            </ns0:station>
            <ns0:limit>1</ns0:limit>
          </ns0:getStations>
        </env:Body>
      </env:Envelope>
    ))

    expect(Nokogiri.XML(operation.to_xml))
      .to be_equivalent_to(expected).respecting_element_order
  end
end
