# frozen_string_literal: true

module WSDL
  module Security
    # Fluent facade for configuring request and response security policies.
    #
    # Config is intentionally thin and delegates to focused components:
    # - {RequestPolicy} for outbound message security intent
    # - {ResponsePolicy} for inbound verification enforcement
    # - {CredentialNormalizer} for credential normalization and validation
    #
    # Per-request runtime security artifacts (nonce, IDs, timestamps, references)
    # are generated by {RequestMaterializer} to avoid replayable state reuse.
    class Config
      # Local alias for key reference constants
      KeyRef = Constants::KeyReference

      # @param policy [Policy]
      # @param credential_normalizer [CredentialNormalizer]
      def initialize(policy: Policy.default, credential_normalizer: CredentialNormalizer.new)
        @policy = policy
        @credential_normalizer = credential_normalizer
      end

      # Configures UsernameToken authentication.
      #
      # @param username [String] the username
      # @param password [String] the password
      # @param digest [Boolean] whether to use digest authentication
      # @param created_at [Time, nil] optional fixed creation timestamp
      # @return [self]
      def username_token(username, password, digest: false, created_at: nil)
        token = RequestPolicy::UsernameToken.new(username:, password:, digest:, created_at:)
        @policy = @policy.with_request(@policy.request.with_username_token(token))
        self
      end

      # Configures a wsu:Timestamp header.
      #
      # @param created_at [Time, nil] optional fixed creation time
      # @param expires_in [Integer] seconds until expiration
      # @param expires_at [Time, nil] explicit expiration time
      # @return [self]
      def timestamp(created_at: nil, expires_in: Timestamp::DEFAULT_TTL, expires_at: nil)
        ts = RequestPolicy::Timestamp.new(created_at:, expires_in:, expires_at:)
        @policy = @policy.with_request(@policy.request.with_timestamp(ts))
        self
      end

      # Configures X.509 certificate signing.
      #
      # SOAP Body signing is mandatory and cannot be disabled.
      #
      # @param certificate [OpenSSL::X509::Certificate, String]
      # @param private_key [OpenSSL::PKey::RSA, OpenSSL::PKey::EC, String]
      # @param options [Hash] signing options
      # @return [self]
      def signature(certificate:, private_key:, **options)
        cert = @credential_normalizer.normalize_certificate(certificate)
        key = @credential_normalizer.normalize_private_key(private_key, options[:key_password])

        signature_options = SignatureOptions.from_hash(options).freeze
        @credential_normalizer.validate_key_reference!(signature_options.key_reference, cert)

        signature = RequestPolicy::Signature.new(
          certificate: cert,
          private_key: key,
          options: signature_options
        )

        @policy = @policy.with_request(@policy.request.with_signature(signature))
        self
      end

      # Configures response verification enforcement.
      #
      # @param mode [Symbol] :disabled, :if_present, or :required
      # @param trust_store [OpenSSL::X509::Store, Symbol, String, Array, nil]
      # @param check_validity [Boolean]
      # @param validate_timestamp [Boolean]
      # @param clock_skew [Integer]
      # @return [self]
      def verify_response(mode: ResponsePolicy::MODE_REQUIRED, trust_store: nil,
                          check_validity: true, validate_timestamp: true, clock_skew: 300)
        resolved_trust_store = resolve_trust_store(mode:, trust_store:)

        options = ResponseVerification::Options.new(
          certificate: ResponseVerification::Certificate.new(
            trust_store: resolved_trust_store,
            verify_not_expired: check_validity
          ),
          timestamp: ResponseVerification::Timestamp.new(
            validate: validate_timestamp,
            tolerance_seconds: clock_skew
          )
        )

        response = @policy.response.with_mode(mode).with_options(options)
        @policy = @policy.with_response(response)
        self
      end

      # Returns whether response verification enforcement is enabled.
      #
      # @return [Boolean]
      def verify_response?
        !@policy.response.disabled?
      end

      # Returns whether any request security is configured.
      #
      # @return [Boolean]
      def configured?
        @policy.request.configured?
      end

      # Returns whether UsernameToken is configured.
      #
      # @return [Boolean]
      def username_token?
        @policy.request.username_token?
      end

      # Returns whether Timestamp is configured.
      #
      # @return [Boolean]
      def timestamp?
        @policy.request.timestamp?
      end

      # Returns whether X.509 signing is configured.
      #
      # @return [Boolean]
      def signature?
        @policy.request.signature?
      end

      # Returns whether timestamp signing is enabled.
      #
      # @return [Boolean]
      def sign_timestamp?
        @policy.request.sign_timestamp?
      end

      # Returns whether WS-Addressing signing is enabled.
      #
      # @return [Boolean]
      def sign_addressing?
        @policy.request.sign_addressing?
      end

      # Returns whether explicit signature namespace prefixes are enabled.
      #
      # @return [Boolean]
      def explicit_namespace_prefixes?
        @policy.request.explicit_namespace_prefixes?
      end

      # Returns key reference method.
      #
      # @return [Symbol]
      def key_reference
        @policy.request.key_reference
      end

      # Returns configured response verification trust store.
      #
      # @return [OpenSSL::X509::Store, Symbol, String, Array, nil]
      def verification_trust_store
        response_verification_options.certificate.trust_store
      end

      # Returns whether certificate validity checking is enabled.
      #
      # @return [Boolean]
      def check_certificate_validity
        response_verification_options.certificate.verify_not_expired
      end

      # Returns whether response timestamp validation is enabled.
      #
      # @return [Boolean]
      def validate_timestamp
        response_verification_options.timestamp.validate
      end

      # Returns response timestamp clock skew in seconds.
      #
      # @return [Integer]
      def clock_skew
        response_verification_options.timestamp.tolerance_seconds
      end

      # Returns response verification mode.
      #
      # @return [Symbol]
      def verification_mode
        @policy.response.mode
      end

      # Returns response verification options.
      #
      # @return [ResponseVerification::Options]
      def response_verification_options
        @policy.response.options
      end

      # Returns the response policy for verification enforcement.
      #
      # @return [ResponsePolicy]
      def response_policy
        @policy.response
      end

      # Builds per-request runtime security context.
      #
      # @param now [Time]
      # @return [RequestContext]
      def request_context(now: Time.now.utc)
        RequestMaterializer.materialize(@policy.request, now:)
      end

      # Clears all security policy.
      #
      # @return [self]
      def clear
        @policy = Policy.default
        self
      end

      # Returns deep-copy style duplicate.
      #
      # @return [Config]
      def dup
        self.class.new(policy: @policy, credential_normalizer: @credential_normalizer)
      end

      # Returns redacted configuration for safe logging.
      #
      # @return [String]
      def inspect
        parts = inspect_base_parts
        parts.concat(inspect_username_token_parts) if @policy.request.username_token
        parts.concat(inspect_signature_parts) if @policy.request.signature
        "#<#{self.class.name} #{parts.join(' ')}>"
      end

      private

      def inspect_base_parts
        [
          "username_token=#{username_token?}",
          "timestamp=#{timestamp?}",
          "signature=#{signature?}",
          "verify_response=#{verify_response?}",
          "verify_mode=#{verification_mode.inspect}"
        ]
      end

      def inspect_username_token_parts
        token = @policy.request.username_token
        [
          "username_token.username=#{token.username.inspect}",
          'username_token.password=[REDACTED]',
          "username_token.digest=#{token.digest}"
        ]
      end

      def inspect_signature_parts
        signature = @policy.request.signature
        cert_subject = signature.certificate.subject.to_s
        [
          "signature.certificate=#{cert_subject.inspect}",
          'signature.private_key=[REDACTED]',
          "signature.algorithm=#{signature.options.digest_algorithm.inspect}"
        ]
      end

      def resolve_trust_store(mode:, trust_store:)
        return :system if mode == ResponsePolicy::MODE_REQUIRED && trust_store.nil?

        trust_store
      end
    end
  end
end
