name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  code-quality:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby-version:
          - '3.3'
          - '3.4'
          - '4.0'

    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Set up Ruby
        uses: ruby/setup-ruby@09a7688d3b55cf0e976497ff046b70949eeaccfd # v1.288.0
        with:
          ruby-version: ${{ matrix.ruby-version }}
          bundler-cache: true

      - name: Run lint
        run: bundle exec rake lint

      - name: Run yard audit
        run: bundle exec rake yard:audit

      - name: Run specs
        run: bundle exec rake spec

  benchmark:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Set up Ruby
        uses: ruby/setup-ruby@09a7688d3b55cf0e976497ff046b70949eeaccfd # v1.288.0
        with:
          ruby-version: '3.4'
          bundler-cache: true

      - name: Run benchmarks
        run: BENCHMARK_OUTPUT=benchmark_results.json bundle exec rake benchmark

      - name: Track benchmark results
        uses: benchmark-action/github-action-benchmark@d48d326b4ca9ba73ca0cd0d59f108f9e02a381c7 # v1.20.4
        with:
          tool: customBiggerIsBetter
          output-file-path: benchmark_results.json
          github-token: ${{ secrets.GITHUB_TOKEN }}
          auto-push: ${{ github.ref == 'refs/heads/main' }}
          alert-threshold: '150%'
          comment-on-alert: true
          fail-on-alert: true
          benchmark-data-dir-path: dev/benchmark
